In [2]:
from importlib.metadata import version
import torch
import torch.nn.functional as F

print("torch version:", version("torch"))
print(torch.cuda.is_available() )

torch version: 2.7.1
True


In [3]:
x = torch.randn(2, 3)

In [4]:
print(x)
print(x.shape)

tensor([[-1.4889, -0.5853, -0.4802],
        [-1.7643, -1.4507,  0.9602]])
torch.Size([2, 3])


In [5]:
torch.cat((x, x, x), 0)

tensor([[-1.4889, -0.5853, -0.4802],
        [-1.7643, -1.4507,  0.9602],
        [-1.4889, -0.5853, -0.4802],
        [-1.7643, -1.4507,  0.9602],
        [-1.4889, -0.5853, -0.4802],
        [-1.7643, -1.4507,  0.9602]])

In [6]:
torch.cat((x, x, x), 1)

tensor([[-1.4889, -0.5853, -0.4802, -1.4889, -0.5853, -0.4802, -1.4889, -0.5853,
         -0.4802],
        [-1.7643, -1.4507,  0.9602, -1.7643, -1.4507,  0.9602, -1.7643, -1.4507,
          0.9602]])

In [7]:
# (b, num_heads, num_tokens, head_dim) = (1, 2, 3, 4)
a = torch.tensor([[[[0.2745, 0.6584, 0.2775, 0.8573],
                    [0.8993, 0.0390, 0.9268, 0.7388],
                    [0.7179, 0.7058, 0.9156, 0.4340]],

                   [[0.0772, 0.3565, 0.1479, 0.5331],
                    [0.4066, 0.2318, 0.4545, 0.9737],
                    [0.4606, 0.5159, 0.4220, 0.5786]]]])

In [8]:
a.shape 

torch.Size([1, 2, 3, 4])

In [11]:
x = torch.randn(2, 3)
print(x.is_contiguous())      # False

y = x.transpose(0, 1)         # Makes x non-contiguous in memory
print(y.is_contiguous())      # False

y_contig = y.contiguous()
print(y_contig.is_contiguous())  # True

True
False
True


In [12]:
print(a @ a.transpose(2, 3))

tensor([[[[1.3208, 1.1631, 1.2879],
          [1.1631, 2.2150, 1.8424],
          [1.2879, 1.8424, 2.0402]],

         [[0.4391, 0.7003, 0.5903],
          [0.7003, 1.3737, 1.0620],
          [0.5903, 1.0620, 0.9912]]]])


In [13]:
first_head = a[0, 0, :, :]

print(f"first_head:{first_head}")
print(f"first_head.shape:{first_head.shape}")

first_res = first_head @ first_head.T
print("First head:\n", first_res)

first_head:tensor([[0.2745, 0.6584, 0.2775, 0.8573],
        [0.8993, 0.0390, 0.9268, 0.7388],
        [0.7179, 0.7058, 0.9156, 0.4340]])
first_head.shape:torch.Size([3, 4])
First head:
 tensor([[1.3208, 1.1631, 1.2879],
        [1.1631, 2.2150, 1.8424],
        [1.2879, 1.8424, 2.0402]])


In [14]:
second_head = a[0, 1, :, :]
second_res = second_head @ second_head.T
print("\nSecond head:\n", second_res)


Second head:
 tensor([[0.4391, 0.7003, 0.5903],
        [0.7003, 1.3737, 1.0620],
        [0.5903, 1.0620, 0.9912]])
