In [1]:
import torch

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

print(f"inputs.shape:{inputs.shape}")

inputs.shape:torch.Size([6, 3])


In [2]:
x_2 = inputs[1]
print(f"x_2:{x_2}")

x_2:tensor([0.5500, 0.8700, 0.6600])


In [3]:
d_in = inputs.shape[1] # the input embedding size, d=3
d_out = 2 # the output embedding size, d=2

In [4]:
torch.manual_seed(123)

W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key   = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)

In [5]:
query_2 = x_2 @ W_query
key_2 = x_2 @ W_key
value_2 = x_2 @ W_value

print(f"query_2:{query_2}")
print(f"key_2:{key_2}")
print(f"value_2:{value_2}")


query_2:tensor([0.4306, 1.4551])
key_2:tensor([0.4433, 1.1419])
value_2:tensor([0.3951, 1.0037])


In [6]:
keys = inputs @ W_key       # (6, d_out) =  (6, 3) @ (3, 2)
values = inputs @ W_value   # (6, d_out) =  (6, 3) @ (3, 2)

print("keys.shape:", keys.shape)
print("values.shape:", values.shape)

keys.shape: torch.Size([6, 2])
values.shape: torch.Size([6, 2])


In [7]:
print("keys:", keys)
print("values:", values)

keys: tensor([[0.3669, 0.7646],
        [0.4433, 1.1419],
        [0.4361, 1.1156],
        [0.2408, 0.6706],
        [0.1827, 0.3292],
        [0.3275, 0.9642]])
values: tensor([[0.1855, 0.8812],
        [0.3951, 1.0037],
        [0.3879, 0.9831],
        [0.2393, 0.5493],
        [0.1492, 0.3346],
        [0.3221, 0.7863]])


In [8]:
keys_2 = keys[1] # Python starts index at 0
attn_score_22 = query_2.dot(keys_2)
print(attn_score_22)

tensor(1.8524)


In [9]:
print(f"query_2.shape:{query_2.shape}")
print(f"keys_2.shape:{keys_2.shape}")
print(f"keys.shape:{keys.shape}")

query_2.shape:torch.Size([2])
keys_2.shape:torch.Size([2])
keys.shape:torch.Size([6, 2])


In [10]:
query_2 @ keys.T

tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440])

In [11]:
attn_scores_2 = query_2 @ keys.T # All attention scores for given query
print(attn_scores_2)

tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440])


In [12]:
d_k = keys.shape[1]
attn_weights_2 = torch.softmax(attn_scores_2 / d_k**0.5, dim=-1)
print(attn_weights_2)

tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820])


In [13]:
context_vec_2 = attn_weights_2 @ values
print(context_vec_2)

tensor([0.3061, 0.8210])
