In [1]:
import torch

x = torch.tensor([1.0, 2.0, 3.0])
torch.softmax(x, dim=0)


tensor([0.0900, 0.2447, 0.6652])

In [2]:
import torch
import torch.nn.functional as F

x = torch.tensor([1.0, 2.0, 3.0])
F.softmax(x, dim=0)


tensor([0.0900, 0.2447, 0.6652])

In [3]:
import torch
import torch.nn as nn

m = nn.Softmax(dim=0)
x = torch.tensor([1.0, 2.0, 3.0])
m(x)


tensor([0.0900, 0.2447, 0.6652])

In [8]:
a = torch.randn(4, 4)
print(a)

tensor([[-1.6103, -0.0122,  0.1501, -0.1823],
        [ 0.7332, -1.2879,  1.5409, -0.1080],
        [-1.6033, -2.4220,  0.1667,  0.2856],
        [-0.6694, -0.1229, -0.2937, -1.4828]])


In [9]:
torch.tril(a)

tensor([[-1.6103,  0.0000,  0.0000,  0.0000],
        [ 0.7332, -1.2879,  0.0000,  0.0000],
        [-1.6033, -2.4220,  0.1667,  0.0000],
        [-0.6694, -0.1229, -0.2937, -1.4828]])

In [10]:
torch.tril(a, diagonal=1)

tensor([[-1.6103, -0.0122,  0.0000,  0.0000],
        [ 0.7332, -1.2879,  1.5409,  0.0000],
        [-1.6033, -2.4220,  0.1667,  0.2856],
        [-0.6694, -0.1229, -0.2937, -1.4828]])

In [11]:
torch.tril(a, diagonal=2)

tensor([[-1.6103, -0.0122,  0.1501,  0.0000],
        [ 0.7332, -1.2879,  1.5409, -0.1080],
        [-1.6033, -2.4220,  0.1667,  0.2856],
        [-0.6694, -0.1229, -0.2937, -1.4828]])

In [12]:
torch.triu(a)

tensor([[-1.6103, -0.0122,  0.1501, -0.1823],
        [ 0.0000, -1.2879,  1.5409, -0.1080],
        [ 0.0000,  0.0000,  0.1667,  0.2856],
        [ 0.0000,  0.0000,  0.0000, -1.4828]])

In [13]:
torch.triu(a, diagonal=1)

tensor([[ 0.0000, -0.0122,  0.1501, -0.1823],
        [ 0.0000,  0.0000,  1.5409, -0.1080],
        [ 0.0000,  0.0000,  0.0000,  0.2856],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])

In [14]:
torch.triu(torch.ones(4, 4), diagonal=1)

tensor([[0., 1., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [15]:
torch.bool?

Type:        dtype
String form: torch.bool
File:        ~/miniconda3/envs/pytorch_gpu_0710/lib/python3.10/site-packages/torch/__init__.py
Docstring:   <no docstring>

In [18]:
x = torch.tensor([1.0, 0, 3])
x.softmax(dim=0)

tensor([0.1142, 0.0420, 0.8438])

In [28]:
mask = torch.triu(torch.ones(4, 4), diagonal=1)
print(f"mask:{mask}")
print(f"mask.shape:{mask.shape}")

mask:tensor([[0., 1., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])
mask.shape:torch.Size([4, 4])


In [29]:
print(a.shape)
print(mask.shape)
assert a.shape == mask.shape

torch.Size([4, 4])
torch.Size([4, 4])


In [30]:
masked = torch.masked_fill(a, mask.bool(), -torch.inf)
print(masked)

tensor([[-1.6103,    -inf,    -inf,    -inf],
        [ 0.7332, -1.2879,    -inf,    -inf],
        [-1.6033, -2.4220,  0.1667,    -inf],
        [-0.6694, -0.1229, -0.2937, -1.4828]])


In [34]:
masked = a.masked_fill(mask.bool(), -torch.inf)
print(masked)

tensor([[-1.6103,    -inf,    -inf,    -inf],
        [ 0.7332, -1.2879,    -inf,    -inf],
        [-1.6033, -2.4220,  0.1667,    -inf],
        [-0.6694, -0.1229, -0.2937, -1.4828]])


In [35]:
mask.bool()

tensor([[False,  True,  True,  True],
        [False, False,  True,  True],
        [False, False, False,  True],
        [False, False, False, False]])

In [40]:
torch.manual_seed(123)
dropout = torch.nn.Dropout(0.9) # dropout rate of 50%
example = torch.ones(6, 6) # create a matrix of ones

print(dropout(example))

tensor([[ 0., 10.,  0., 10.,  0.,  0.],
        [ 0.,  0.,  0., 10.,  0., 10.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., 10.,  0.,  0.]])
