In [2]:
import torch

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [3]:
query = inputs[1]

In [4]:
print(query)

tensor([0.5500, 0.8700, 0.6600])


In [6]:
query.size()

torch.Size([3])

In [7]:
inputs.size()

torch.Size([6, 3])

In [9]:
torch.dot(torch.tensor([1,2,3]), torch.tensor([4,5,6]))

tensor(32)

In [10]:
query = inputs[1]  # 2nd input token is the query

attn_scores_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query) # dot product (transpose not necessary here since they are 1-dim vectors)

print(attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [19]:
print(query.shape)
print(inputs.shape)
print(torch.t(inputs).shape)
print(torch.matmul(query, torch.t(inputs)))

torch.Size([3])
torch.Size([6, 3])
torch.Size([3, 6])
tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [21]:
attn_scores_3 = torch.matmul(query, torch.t(inputs))
attn_weights_3_tmp = attn_scores_3 / attn_scores_3.sum()

print("Attention weights:", attn_weights_3_tmp)
print("Sum:", attn_weights_3_tmp.sum())

Attention weights: tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
Sum: tensor(1.0000)


In [22]:
torch.exp(attn_scores_3)

tensor([2.5971, 4.4593, 4.3728, 2.3243, 2.0279, 2.9639])

In [24]:
def softmax_naive(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)

attn_weights_3_naive = softmax_naive(attn_scores_3)

print("Attention weights:", attn_weights_3_naive)
print("Sum:", attn_weights_3_naive.sum())

Attention weights: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum: tensor(1.)


In [68]:
x = torch.matmul(inputs, torch.t(inputs))
print(x)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [40]:
torch.allclose(x[1], attn_scores_3, atol=1e-6)

True

In [41]:
x[1] == attn_scores_3

tensor([False,  True,  True,  True,  True,  True])

In [32]:
x[1] == attn_scores_3

tensor([False,  True,  True,  True,  True,  True])

In [62]:
x = torch.tensor([[1.0, 1.0, 1.0],
                  [1.0, 1.0, 1.0]])
y = torch.exp(x)
print(y.shape)
print(y)

torch.Size([2, 3])
tensor([[2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183]])


In [64]:
torch.sum(y, dim=1, keepdims=True)

tensor([[8.1548],
        [8.1548]])

In [69]:
def softmax_rows(x):
    return torch.exp(x) / torch.exp(x).sum(dim=1, keepdims=True)

print(x)
print(softmax_rows(x))

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])
tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [66]:
torch.exp(x)

tensor([[2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183]])

In [72]:
y = torch.softmax(x, dim=1)

In [73]:
torch.sum(y, dim=1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [74]:
print(y)
print(y.shape)


tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])
torch.Size([6, 6])


In [75]:
y @ inputs

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])