In [1]:
import torch
torch.__version__

'2.7.1+cpu'

In [2]:
torch.cuda.is_available() 

False

In [3]:
tensor0d = torch.tensor(1)
print(tensor0d)

tensor(1)


In [4]:
# create a 1D tensor (vector) from a Python list
tensor1d = torch.tensor([1, 2, 3])

# create a 2D tensor from a nested Python list
tensor2d = torch.tensor([[1, 2], [3, 4]])

# create a 3D tensor from a nested Python list
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [6]:
tensor2d.shape

torch.Size([2, 2])

In [11]:
tensor2d = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])

In [12]:
tensor2d.shape

torch.Size([2, 3])

In [13]:
x = tensor2d.reshape(3,2)

In [14]:
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [16]:
y = tensor2d.view(3,2)

In [17]:
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
y

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [23]:
import torch

x1 = torch.arange(6)
x2 = x1.reshape(2, 3)  # Always works
x3 = x2.view(3, 2)     # Works only if x is contiguous


In [24]:
x1

tensor([0, 1, 2, 3, 4, 5])

In [25]:
x2

tensor([[0, 1, 2],
        [3, 4, 5]])

In [26]:
x3

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [27]:
tensor2d = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])

In [28]:
tensor2d.matmul(tensor2d.T)

tensor([[14, 32],
        [32, 77]])

In [29]:
tensor2d @ tensor2d.T

tensor([[14, 32],
        [32, 77]])