In [14]:
import torch

print(torch.cuda.is_available() )
a = torch.randn(4, 4)
n = a.shape[0]

print(a)
print(n)
print(a.size(0))

True
tensor([[ 0.8739, -0.4301,  0.1873, -1.0778],
        [ 1.1944,  0.6228, -1.9724, -0.9417],
        [-0.2969,  1.1913, -0.2543, -0.4689],
        [ 0.8337,  1.2896, -0.4328,  1.2011]])
4
4


In [15]:
mask = torch.ones(n , n)
print(mask)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [16]:
torch.triu(a)

tensor([[ 0.8739, -0.4301,  0.1873, -1.0778],
        [ 0.0000,  0.6228, -1.9724, -0.9417],
        [ 0.0000,  0.0000, -0.2543, -0.4689],
        [ 0.0000,  0.0000,  0.0000,  1.2011]])

In [25]:
tl = torch.tril(a)
print(tl)

tl_bool =  torch.tril(a).bool()
print(tl_bool)

tensor([[ 0.8739,  0.0000,  0.0000,  0.0000],
        [ 1.1944,  0.6228,  0.0000,  0.0000],
        [-0.2969,  1.1913, -0.2543,  0.0000],
        [ 0.8337,  1.2896, -0.4328,  1.2011]])
tensor([[ True, False, False, False],
        [ True,  True, False, False],
        [ True,  True,  True, False],
        [ True,  True,  True,  True]])


In [18]:
torch.triu(a)

tensor([[ 0.8739, -0.4301,  0.1873, -1.0778],
        [ 0.0000,  0.6228, -1.9724, -0.9417],
        [ 0.0000,  0.0000, -0.2543, -0.4689],
        [ 0.0000,  0.0000,  0.0000,  1.2011]])

In [23]:
tu = torch.triu(a, diagonal=1)
print(tu)

tu_bool = tu.bool()
print(tu_bool)

tensor([[ 0.0000, -0.4301,  0.1873, -1.0778],
        [ 0.0000,  0.0000, -1.9724, -0.9417],
        [ 0.0000,  0.0000,  0.0000, -0.4689],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])
tensor([[False,  True,  True,  True],
        [False, False,  True,  True],
        [False, False, False,  True],
        [False, False, False, False]])


In [24]:
torch.masked_fill(a, tu_bool, -torch.inf)

tensor([[ 0.8739,    -inf,    -inf,    -inf],
        [ 1.1944,  0.6228,    -inf,    -inf],
        [-0.2969,  1.1913, -0.2543,    -inf],
        [ 0.8337,  1.2896, -0.4328,  1.2011]])